- Makefile
- auth.go
- examples/grpcc/Dockerfile
- glide.lock
- glide.yaml
- main.go
- vendor/github.com/hkwi/h2c/LICENSE
- vendor/github.com/hkwi/h2c/example_test.go
- vendor/github.com/hkwi/h2c/server.go
> Initial support for http/2(h2, h2c) and gRPC clients/upstream severs

- Dockerfile
- Makefile
- examples/rewrites/deployment.yaml
- examples/rewrites/rbac.yaml
- examples/rewrites/resource-attributes.yaml
- main.go
- pkg/authz/auth.go
- pkg/proxy/proxy.go
This PR adds rewrite functionality based on query parameters of an URL. For example, when configured to the `namespace` query parameter then the value passed in a request can be templated in the SubjectAccessReview done against the Kubernetes API. This allows SubjectAccessReviews to be dependent on the parameter passed. For example this can be used with the [prom-label-proxy](https://github.com/openshift/prom-label-proxy) to validate that a requesting user (or Prometheus server) is allowed to access metrics for a certain namespace, and if so it is passed onto the label proxy through, which then enforces the PromQL query to have the respective namespace in the query.
If a rewrite by parameter is configured but no parameter is given, then the request is returned as a `BadRequest`. …
> *: Add rewrite functionality of SubjectAccessReview requests

- Dockerfile
Same as this: https://github.com/openshift/kube-rbac-proxy/pull/4
> Remove hardcoded amd64 to allow multi-arch builds

- Dockerfile
- main.go
When starting a server we should check their return values and log them.
Additionally, we should think about using something like `run.Group` to terminate all goroutines if one server fails.
/cc @brancz @squat @mxinden
> Check errors and log them

- Makefile
- pkg/proxy/proxy_test.go
apiserver.authenticator in [kube 1.11](https://github.com/kubernetes/kubernetes/blob/release-1.11/staging/src/k8s.io/apiserver/pkg/authentication/authenticator/interfaces.go#L47)
vs
[kube 1.13](https://github.com/kubernetes/kubernetes/blob/release-1.13/staging/src/k8s.io/apiserver/pkg/authentication/authenticator/interfaces.go#L46)
Which is what's now in glide.yaml.
make test output:
```
>> running all tests
?   	github.com/brancz/kube-rbac-proxy	[no test files]
?   	github.com/brancz/kube-rbac-proxy/pkg/authn	[no test files]
?   	github.com/brancz/kube-rbac-proxy/pkg/authz	[no test files]
ok  	github.com/brancz/kube-rbac-proxy/pkg/proxy	0.019s
```
> Fix proxy test

- .travis.yml
- Makefile
- test/e2e/basics.go
- test/e2e/basics/clusterRole-client.yaml
- test/e2e/basics/clusterRole.yaml
- test/e2e/basics/clusterRoleBinding-client.yaml
- test/e2e/basics/clusterRoleBinding.yaml
- test/e2e/basics/deployment.yaml
- test/e2e/basics/service.yaml
- test/e2e/basics/serviceAccount.yaml
- test/e2e/main_test.go
- test/kubetest/kubernetes.go
- test/kubetest/kubetest.go
This PR adds a basic end to end test for kube-rbac-proxy.
The most basic test simply `curl`s a deployment that is guarded by the kube-rbac-proxy. The first one tests if the client fails, if not sufficient rights and the second tests checks if the clients succeeds with the correct rbac rules added.
TODO:
> Create basic end to end tests with kubetest framework

- test/e2e/basics.go
- test/e2e/main_test.go
- test/kubetest/kubernetes.go
- test/kubetest/kubetest.go
Currently running `make check-license` fails with the error:
```
$ make check-license
>> checking license headers
-e license header checking failed:
-e   ./test/kubetest/kubetest.go
-e   ./test/kubetest/kubernetes.go
-e   ./test/e2e/basics.go
-e   ./test/e2e/main_test.go
make: *** [check-license] Error 255
```
This PR adds headers to the relevant files, so license check doesn't fail.
> Fixing license headers

- Makefile
On aarch64, GOARCH is 'arm64'.  Instead of making this even longer, just get GOARCH from go itself.
> Use go env GOARCH in Makefile

- main.go
- pkg/tls/reloader.go
- pkg/tls/reloader_test.go
TODOs:
This is an implementation as discussed in https://github.com/brancz/kube-rbac-proxy/pull/45#discussion_r295295712, ready for an initial pass.
I am keeping the other PR open to scavenge the code for the prometheus config reloader implementation.
> *: watch tls certificate changes

- .gitignore
- .travis.yml
- Dockerfile
- Makefile
- use gcr.io/distroless/static as it already has ca-certificates built-in and is cross-platform
- allow building multi-arch images (modeled after https://github.com/jimmidyson/configmap-reload/blob/master/Makefile)
- automate building images when new tag is pushed
Last feature needs adding quay credentials to travis CI. Following vairables need to be added:
- `QUAY_USERNAME`
- `QUAY_PASSWORD`
> Build process refactor

- .travis.yml
I think it would be nice to have images pushed to quay for every hash,
that would enable better testing. This commit makes it so that every
commit merged to master results in an image pushed to quay tagged like:
master-2020-05-06-37157950.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
cc @paulfantom
> .travis.yaml: push images tagged with hash

- .travis.yml
PR #70 introduced new scripts into the .travis.yml file, which did not
correctly escape `&` characters, which are anchors in YAML.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> .travis: quote ampersands

- .travis.yml
Currently CI cannot push images due to https://github.com/docker/for-linux/issues/396. This is a workaround which is confirmed to work and was already applied in [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator/pull/3184)
cc @squat
> Fix pushing images to quay.io

- .travis.yml
Shell test result is passed as the exit code:
```
sh-5.0$ [ -n "$TRAVIS_TAG" ] && echo "OK"
sh-5.0$ echo $?
1
```
This causes incorrect test results.
/cc @brancz
> .travis: do not fail when variables are not defined

- Dockerfile
- examples/non-resource-url-token-request/deployment.yaml
- examples/non-resource-url/deployment.yaml
- examples/non-resource-url/non-resource-url/deployment.yaml
- examples/oidc/deployment.yaml
- examples/resource-attributes/deployment.yaml
- examples/rewrites/deployment.yaml
- scripts/templates/non-resource-url-deployment.yaml
- scripts/templates/non-resource-url-token-request-deployment.yaml
- scripts/templates/oidc-deployment.yaml
- scripts/templates/resource-attributes-deployment.yaml
- scripts/templates/rewrites-deployment.yaml
**Description**
- Make the docker image be rootless
**Motivation**
- https://github.com/kubernetes-sigs/kubebuilder/issues/1637
- Closes: https://github.com/brancz/kube-rbac-proxy/issues/84
- Following the good practices. See;  https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/
> Make image be rootless

- README.md
- main.go
- test/e2e/basics.go
- test/e2e/ignorepaths/clusterRole-client.yaml
- test/e2e/ignorepaths/clusterRole.yaml
- test/e2e/ignorepaths/clusterRoleBinding-client.yaml
- test/e2e/ignorepaths/clusterRoleBinding.yaml
- test/e2e/ignorepaths/deployment.yaml
- test/e2e/ignorepaths/service.yaml
- test/e2e/ignorepaths/serviceAccount.yaml
- test/e2e/main_test.go
Do not perform any auth check if the request path matches any specified by the new ignore-paths flag, just proxy. Closes #25 
I *think* this can live alongside `--allow-paths` but interested to hear your thoughts.
> Add support for ignore-paths

- go.mod
- go.sum
- main.go
- pkg/proxy/proxy.go
- pkg/tls/reloader.go
- pkg/tls/reloader_test.go
Move to klog v2 for compatibility reasons.
cc @s-urbaniak
> *: move to klog v2

- examples/rewrites/README.md
`non-resoruces` -> `non-resources`
> Fixing a small typo in examples/rewrites/README.md

- .github/workflows/build.yml
- .gitignore
- Makefile
- README.md
- examples/non-resource-url-token-request/README.md
- examples/non-resource-url-token-request/deployment.yaml
- examples/non-resource-url/README.md
- examples/non-resource-url/deployment.yaml
- examples/non-resource-url/non-resource-url/README.md
- examples/oidc/deployment.yaml
- examples/resource-attributes/README.md
- examples/resource-attributes/deployment.yaml
- examples/rewrites/README.md
- examples/rewrites/deployment.yaml
- pkg/proxy/proxy_test.go
- pkg/tls/reloader_test.go
- scripts/generate-help-txt.sh
- scripts/go.mod
- scripts/go.sum
- scripts/tools.go
While running kube-rbac-proxy unit tests locally, I noticed that these tests were failing, so while fixing them I also improved the CI coverage so that such failures could be catch early on. These improvements include the following changes:
Split the create-cluster job into 2 seperate jobs:
- e2e-tests
- publish
Add the following ci jobs from existing Makefile rules:
- check-license
- generate
- build
- unit-tests
Adding the generate job showed failures in the generation scripts, so I fixed them as part of this PR.
> Improve CI coverage and fix existing failures

- .github/workflows/build.yml
The following CI run failed because of a typo in the publish job: https://github.com/brancz/kube-rbac-proxy/runs/1577096032
> .github/workflows: fix typo in publish job

- .github/workflows/build.yml
There is another problem with the publish job: https://github.com/brancz/kube-rbac-proxy/runs/1589263350
While splitting the create-cluster job into the e2e-test and publish jobs, I had forgotten to duplicate the container build.
> .github/workflows: fix image publication

- Makefile
- go.mod
- go.sum
- pkg/authz/auth.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
**Description**
This PR extends the SubjectAccessReviews rewrite functionality by allowing to rewrite the attributes using a value from http header.
**Motivation**
I would like to put kube-rbac-proxy in front of Loki (https://grafana.com/docs/loki/latest/). Loki, when deployed in multi-tenant mode, requires X-Scope-OrgID header containing the tenantID. In my case, the tenantID is just the namespace and so I could check if a given user/SA has access to a particular resource in a given namespace provided in the X-Scope-OrgID header. This way I could separate the logs on a per namespace basis.
> Rewrite from header

- examples/example-client-urlquery/Dockerfile
- examples/rewrites/README.md
Seems like the resource-attributes example was largely just copied and
the description did not match the config fragments.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> examples: fix rewrite example

- Makefile
- examples/example-client/Dockerfile
- examples/non-resource-url-token-request/README.md
- examples/non-resource-url-token-request/client.yaml
- examples/non-resource-url-token-request/wrong-client.yaml
- examples/non-resource-url/README.md
- examples/non-resource-url/client.yaml
- examples/non-resource-url/non-resource-url/README.md
- examples/non-resource-url/non-resource-url/client.yaml
- examples/resource-attributes/README.md
- examples/resource-attributes/client.yaml
- main.go
- scripts/kind-load-local.sh
- test/e2e/basics.go
- test/e2e/main_test.go
- test/e2e/tls.go
This adds support for TLS 1.3.
Note: I also updated the krp-curl image to use a TLS 1.3 enabled Alpine image version 3.12 in https://quay.io/repository/brancz/krp-curl?tag=latest&tab=tags.
cc @kakkoyun @brancz @simonpasquier
> Support TLS v1.3

- Makefile
This should fix the incorrectly assigned CPU architecture in container image manifests. This is mostly a cosmetic change as we set proper CPU architecture in a main virtual manifest.
Example manifest for ppc64le before this change:
```
$ manifest-tool inspect quay.io/brancz/kube-rbac-proxy:v0.9.0-ppc64le
quay.io/brancz/kube-rbac-proxy:v0.9.0-ppc64le: manifest type: application/vnd.docker.distribution.manifest.v2+json
Digest: sha256:56673d4eed7952068952ba84219ffc6693496a2e4fef57ea9bd776fb430fb6a3
Architecture: amd64
OS: linux
layer 1: digest = sha256:5dea5ec2316d4a067b946b15c3c4f140b4f2ad607e73e9bc41b673ee5ebb99a3
layer 2: digest = sha256:ea0eb814dc9409f25a39a903ad26b0e1d137f7fbfc3e61be8adf8dddb2d2ede2
```
After this change:
```
$ manifest-tool inspect …
```
> Makefile: correctly annotate container image designated platform

- pkg/authn/delegating.go
Setting a nil-value typed object in the `DelegatingAuthenticatorConfig`
will cause the generic logic to still evaluate is as non-nil since
Golang does not consider `(*type)(nil)` as `nil` in `== nil` comparison
unless `type == nil`, too.
This leads to a setup of an x509 authenticator that attempts to call
`VerifyOptions` on a nil object.
fixes https://github.com/brancz/kube-rbac-proxy/issues/131
> Prevent panics on client-cert authenticated requests

- .github/workflows/build.yml
- .golangci.yaml
- main.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
- pkg/tls/reloader_test.go
A bit different approach than proposed in #134 as linter is added only in CI, but this would also catch issues like one from #131 without needing to manage tooling dependency.
Fixes https://github.com/brancz/kube-rbac-proxy/issues/134
cc @s-urbaniak
> .github/workflows: enable golangci-lint

- main.go
- test/e2e/allowpaths/deployment.yaml
- test/e2e/basics.go
- test/e2e/ignorepaths/deployment.yaml
This pull request make it possible to use URL patterns matching.
For example, we can use --allow-paths="/pre/fix1/*" to allow URL such as "/pre/fix1/AAA", "/pre/fix1/BBB"
We intent to make it possible to proxy requests using URL suffixes delimited by slashes as a method to pass arguments, such as [this uses case](https://issues.redhat.com/browse/MON-1695) to pass through query of label values to Prometheus. The URL can be /api/v1/label/<name>/values. Because keeping an exhaust list of labels' names is both time-costing and complicated especially when new labels are created during runtime. So we believe allowing pattern match for URL is a good solution.
> allow path patterns in --allow-paths and --ignore-paths

- main.go
- scripts/kind-load-local.sh
- test/e2e/h2c-upstream/clusterRole-client.yaml
- test/e2e/h2c-upstream/clusterRole.yaml
- test/e2e/h2c-upstream/clusterRoleBinding-client.yaml
- test/e2e/h2c-upstream/clusterRoleBinding.yaml
- test/e2e/h2c-upstream/deployment.yaml
- test/e2e/h2c-upstream/service.yaml
- test/e2e/h2c-upstream/serviceAccount.yaml
- test/e2e/h2c_upstream.go
- test/e2e/main_test.go
Upstream-force-h2c is a flag for upstream, while insecure-listen-address is for the proxy endpoint. Both can work
separately. One use case is having a secure terminating endpoint with kube-rbac-proxy while having an insecure upstream.
Signed-off-by: Andy Librian <andylibrian@gmail.com>
ref: #139
> chore: move --upstream-force-h2c out of --insecure-listen-address #139

- .github/workflows/build.yml
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
- set go-version on build workflow to 1.17.9
- remove dead code: DeepCopy
- check for all headers, not just the first entry, when creating AttributesRecords
- go version 1.17.8 and 1.17.9 have security fixes
- unused code is bad code
- don't give the impression that a second header is checked, even though it isn't
> check all headers, go version bump

- main.go
- pkg/proxy/proxy.go
- Add explicit default method for `resourceAttributes`. The behavior shouldn't change.
- Return an internal error on misconfigured regex. Shouldn't change behavior. As it is checked during parsing.
- An unspecified method could make it harder to understand, why a SAR gets rejected.
- It is safer to handle the error case with a 500, even thought is currently can't happen.
https://github.com/brancz/kube-rbac-proxy/issues/169
> Minor Pre-Acceptance: Set default method, return 500s on broken path regex.

- test/e2e/basics.go
- test/e2e/h2c_upstream.go
- test/e2e/main_test.go
- test/e2e/static_authorizer.go
- test/e2e/tls.go
- test/kubetest/client.go
- test/kubetest/kubernetes.go
- test/kubetest/kubetest.go
- Reduce abstractions
- Remove unused code
- Fix minor issues
- Rename into less abstract names
There are so many abstractions, that it takes quite a while to understand the tests:
- Remove suite, use client directly.
Fix:
- Wrong nil check is done in Run function.
- Unnecessary usage of `[]Check`, `[]Setup` in tests.
There is unused code that doesn't work:
- Create random Namespace is never used and doesn't work, without breaking the tests.
- Timeout is not implemented.
Rename:
- It is hard to understand what a Finalizer does, a CleanUp is more common
- Setup, Condition and Check do the exact same thing. There is no need for code duplication.
> Tests e2e reduce abstraction

- go.mod
- go.sum
We are not affected by the CVE directly or indirectly. CVE scanners push
people to create issues against our repository.
> bump: emicklei/go-restful due to CVE-2022-1996

- main.go
- pkg/tls/reloader.go
- pkg/tls/reloader_test.go
- test/kubetest/kubernetes.go
- transport.go
Warnings for insecure use of kube-rbac-proxy.
- [Issue](https://github.com/brancz/kube-rbac-proxy/issues/187)
- [Implementation](https://github.com/brancz/kube-rbac-proxy/pull/186)
> main.go: add warn logs when insecure opts in use

- pkg/authz/auth.go
Improve Naming.
Better understanding of what the code does.
https://github.com/brancz/kube-rbac-proxy/pull/162#discussion_r834551921
> pkg/authz: rename Equal to Matches

- main.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Remove unused args.
Creates noise and unnecessary imports.
- [deads' comment](https://github.com/brancz/kube-rbac-proxy/pull/162#discussion_r834559249)
> pkg/proxy: rm unused args

- main.go
Remove Interval for TLS reloading.
https://github.com/brancz/kube-rbac-proxy/issues/196
> main.go: warning for --tls-reload-interval

- main.go
- pkg/filters/path.go
- pkg/filters/path_test.go
Move allow path logic into a filter.
This is part of a bigger refactoring around the filters for the proxy.
It should make the code easier to read and unit-tested.
> Allow path as filter

- README.md
- main.go
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
There is no way to ensure that the proxy itself is safe and sound. One option is to use health checks of an upstream, but in the case of upstream unavailability, both upstream and kube-rbac-proxy will be restarted.
This PR adds an option to optionally configure a health path.
I also fixed some typos.
> feat: Add healthz path

- README.md
- main.go
- pkg/authn/config.go
- transport.go
- transport_test.go
This PR exposes the options to specify client cert/key pair for https://github.com/brancz/kube-rbac-proxy/issues/169
/assign @ibihim
> add client cert auth for upstream connections

- README.md
- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/options.go
- test/e2e/allowpaths/deployment.yaml
Using a port as a namespace for endpoints specific to the proxy is a bit more practical than using a path/subpath for each specific endpoint/endpoints as this introduced approach is less prone to upstream endpoint changes.
/assign @ibihim 
/cc @nabokihms
> use a different port for proxy-specific endpoints

- .github/workflows/build.yml
Bump golang version to 1.19.4. 
This should fix couple of different CVEs found in older golang versions.
> Bump golang version to 1.19.4

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
The `endpointsAddr` variable is now properly formatted in the log message
> Use formatted logging function

- README.md
- cmd/kube-rbac-proxy/app/options/proxyoptions.go
- pkg/authorization/rewrite/rewrite.go
This addresses the request to document the authorization configuration from https://github.com/brancz/kube-rbac-proxy/issues/169
> document the authorization config

- Makefile
- README.md
Make `make test-local` work and on other architectures as well.
Currently `make test-local` prints only what needs to be done and it only works on Linux-AMD64.
> Makefile: make local testing work with one command

- .github/workflows/build.yml
- go.mod
This PR updates go lang version in go.mo to 1.20.
It fixes following High Level CVEs:
- [CVE-2023-24534](https://nvd.nist.gov/vuln/detail/CVE-2023-24534)
- [CVE-2023-24536](https://nvd.nist.gov/vuln/detail/CVE-2023-24536)
> bump up go version to 1.20

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
This PR addresses some of the issues from #238; in particular, the ones listed in [this comment](https://github.com/brancz/kube-rbac-proxy/issues/238#issuecomment-1571662143).
In particular:
- (3) Replace func with cobra.Args [link](https://github.com/brancz/kube-rbac-proxy/pull/229/files#diff-8796db11a6b137095413f7a7109dd01393e63d425454fc04647b98d2b8c0115cR106): see 71da752a034bed8df7d4b9da410bd61de4c9f2d1
- (4) Run should run with a final config version. Complete should finish the necessary changes and those shouldn't happen anymore in Run. [link](https://github.com/brancz/kube-rbac-proxy/pull/229/files#diff-8796db11a6b137095413f7a7109dd01393e63d425454fc04647b98d2b8c0115cR166): see b410b9693c63eef2181097da627df19c1c88a338
- (5) Use context from Signals. …
> Minor improvements in cmd/kube-rbac-proxy

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/proxyoptions.go
- cmd/kube-rbac-proxy/app/options/proxyoptions_test.go
- pkg/authorization/rewrite/attributes.go
- pkg/authorization/rewrite/attributes_test.go
- pkg/authorization/rewrite/config.go
- pkg/authorization/rewrite/middleware.go
- pkg/authorization/rewrite/middleware_test.go
- pkg/authorization/rewrite/rewrite.go
- pkg/authorization/rewrite/rewrite_test.go
- Re-order authz-validation-logic to match previous (correct) order.
- Split attributes rewrite from authorizer.Authorizer logic.
- Don't load all variations, even though config picks one.
- Minor improvements from @enj's review.
- The authorization logic is messy.
- Templates are parse per request.
- All authorizers are loaded, even though only one is picked.
> Rewrite rewrite authorizer impl

- .github/workflows/build.yml
- Makefile
Set version values during build time.
Currently we don't set the appropriate version variables and print `Kubernetes v0.0.0-master+$Format:%H$` on `--version`-flag.
> version: set version flag values properly

- .github/workflows/build.yml
- Makefile
Revert VERSION variable change and introduce VERSION_SEMVER, which is a SEMVER version of VERSION.
- Fixes `scripts/publish.sh`
- VERSION is way to complicated to "simply change".
- Solves https://github.com/brancz/kube-rbac-proxy/issues/255
It is way easier to read, when you compare it against `v0.14.2`, rather than `v0.14.3`.
> Makefile: revert VERSION, add VERSION_SEMVER

- .github/workflows/build.yml
- go.mod
- go.sum
- Bump golang version and go dependency `golang.org/x/net` to address [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3)
- More details here https://groups.google.com/g/golang-announce/c/iNNxDTCjZvo
> Bump golang.org/x/net to address CVE-2023-44487

- go.mod
bump opentelemetry.
dumb security scanners go mad.
> deps: patch cve-2023-45142, not affecting krp

- README.md
- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/options.go
- test/e2e/http2.go
- test/e2e/http2/clusterRole-client.yaml
- test/e2e/http2/clusterRole.yaml
- test/e2e/http2/clusterRoleBinding-client.yaml
- test/e2e/http2/clusterRoleBinding.yaml
- test/e2e/http2/deployment-no-http2.yaml
- test/e2e/http2/deployment.yaml
- test/e2e/http2/service.yaml
- test/e2e/http2/serviceAccount.yaml
- test/e2e/main_test.go
- close HTTP/2 connections on unauthenticated users
- set max streams per connection to 100
- set max frame size and stream buffer to 256kb.
- enable to disable HTTP/2 completely
- Golang fixes might be not enough [link](https://github.com/kubernetes/kubernetes/pull/121120)
> proposal for http2: enable to disable, limit http2 resources

- README.md
- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- docs/migration/path.md
- pkg/authorization/path/path.go
- pkg/authorization/path/path_test.go
- test/e2e/allowpaths/deployment.yaml
- test/e2e/basics.go
- Change path-authorizer to act like upstream (only postfix patterns).
- Fail on broken pattern.
- Add unit tests for Ignore-Path-Case
- Upstream doesn't use complex patter matching from the standard library. It is prone to misconfiguration.
- If a broken pattern is given, it behaved like a pattern match.
- There were no unit tests for the Ignore-Path-Case.
> p/a/path: fail on broken pattern early, add tests

- Dockerfile
- Makefile
Right now the Dockerfile uses `gcr.io/distroless/static:nonroot-$GOARCH`, this change just allows us to override the BASEIMAGE file similar to GOARCH / GOOS when using `make`.
I tested a few variations, like this:
```
$ make container
$ DOCKER_REPO=gcr.io/wpanther-gke-dev/kube-rbac-proxy make container
$ DOCKER_REPO=gcr.io/wpanther-gke-dev/kube-rbac-proxy BASEIMAGE=debian:bookworm make container
```
All of them built correctly. I extracted the resulting image from the last one to verify it was updated properly, here's the `PRETTY_NAME` in `etc/os-release`:
```
$ cat ./layer/etc/os-release | grep PRETTY
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
```
Edit: to add some context, I'd like to be able to build `kube-rbac-proxy` with a base image / digest in my own CI/CD for reproducibility. I …
> Allow BASEIMAGE to be overriden at build time

- README.md
- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/options.go
Using kube-rbac-proxy in front of a prometheus in a multi tenant environment causes often client-side throttling events, that slow down connections, when more than 10 queries per second  are coming in. Only way to mitigate is to increase the number of replicas of the kube-rbac-proxy pods.
**Example for client-side throttling**:
I0318 12:32:18.188838     800 request.go:629] Waited for 993.646183ms due to client-side throttling, not priority and fairness, request: POST:https://172.30.0.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews
I0318 12:32:18.192938     800 round_trippers.go:553] POST https://172.30.0.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews 201 Created in 3 milliseconds
I0318 12:32:19.189607     800 request.go:629] Waited for 1.994365552s due to client-side …
> add command line args --kube-api-qps/--kube-api-burst

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/deprecated.go
- cmd/kube-rbac-proxy/app/options/options.go
- test/e2e/flags/deployment-logtostderr.yaml
Fix a regression for the removed flags.
If the bool value flag was specified like `--logtostderr`, without the `=true`, it was treated like `--logtostderr=true` in v0.15.0.
In v0.16.0 and v0.17.0, `--logtostderr` without any value would treat the follow up flag as its value, which leads to a regression.
>  fix bool,deprecated flags regression

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/options/deprecated.go
- cmd/kube-rbac-proxy/app/options/options.go
- test/e2e/flags/deployment-logtostderr.yaml
Fix a regression for the removed flags.
If the bool value flag was specified like `--logtostderr`, without the `=true`, it was treated like `--logtostderr=true` in v0.15.0.
In v0.16.0 and v0.17.0, `--logtostderr` without any value would treat the follow up flag as its value, which leads to a regression.
> Release 0.16.1 fix

- examples/non-resource-url-token-request/README.md
- examples/non-resource-url-token-request/deployment.yaml
- examples/non-resource-url/README.md
- examples/non-resource-url/deployment.yaml
- examples/oidc/deployment.yaml
- examples/resource-attributes/README.md
- examples/resource-attributes/deployment.yaml
- examples/rewrites/README.md
- examples/rewrites/deployment.yaml
- examples/static-auth/README.md
- examples/static-auth/deployment.yaml
- scripts/kind-load-local.sh
- scripts/templates/non-resource-url-deployment.yaml
- scripts/templates/non-resource-url-token-request-deployment.yaml
- scripts/templates/oidc-deployment.yaml
- scripts/templates/resource-attributes-deployment.yaml
- scripts/templates/rewrites-deployment.yaml
- test/e2e/allowpaths/deployment.yaml
- test/e2e/basics/deployment.yaml
- test/e2e/clientcertificates/deployment-wrongca.yaml
- test/e2e/clientcertificates/deployment.yaml
- test/e2e/flags/deployment-logtostderr.yaml
- test/e2e/flags/deployment-other-flags.yaml
- test/e2e/http2/deployment-no-http2.yaml
- test/e2e/http2/deployment.yaml
- test/e2e/ignorepaths/deployment.yaml
- test/e2e/static-auth/deployment.yaml
- test/e2e/tokenrequest/deployment.yaml
v0.1.0 doesn't work by default, at least in minikube. It fails with this error:
Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release
Pulling 0.5.0 works as expected, so running examples should work out of the box.
> Update prometheus-example-app to v0.5.0

- README.md
Seems this was depcreated as part of
https://github.com/brancz/kube-rbac-proxy/issues/196 and a log message warns about it.
> doc: Note that tls-reload-interval is deprecated

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
This was likely a copy-paste error, the clients used in KRP are not loopback apiserver clients.
Fixes https://github.com/brancz/kube-rbac-proxy/issues/317
> include client-go logging

- cmd/kube-rbac-proxy/app/options/options.go
I did not realize https://github.com/brancz/kube-rbac-proxy/pull/299 was a manual change to autogen file, and I thought it was documenting the other option :facepalm:
> code: doc that tls-reload-interval is deprecated

- Makefile
- test/e2e/main_test.go
Use the kube-native way to construct a client by using the KUBECONFIG env var. That was done in the tests anyway (see the change to the Makefile).
The current system promotes using globvars which is a malpractice that should be avoided. It's only confusing new contributors. Let's remove it and just use the KUBECONFIG variable as in the rest of the Kubernetes ecosystem.
> e2e: don't pass client via globvar

- cmd/kube-rbac-proxy/app/kube-rbac-proxy.go
- cmd/kube-rbac-proxy/app/kube-rbac-proxy_test.go
This is to mitigate Golang's behavior with `ReverseProxy.Director` when, after the outgoing request is mutated, any headers specified by "Connection" would get rmoved from the mutated request. `ReverseProxy.Rewrite()` is only called once the headers specified in "Connection" were already removed from the outgoing-to-be request.
Fixes https://github.com/brancz/kube-rbac-proxy/issues/319
*edit*: useful resources for more context: 
- https://www.ory.sh/hop-by-hop-header-vulnerability-go-standard-library-reverse-proxy/
- https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/net/http/httputil/reverseproxy.go;l=386-435
> reverse proxy: use Rewrite instead of Director

- pkg/authn/oidc.go
This PR proposes an alternative approach to https://github.com/brancz/kube-rbac-proxy/issues/259 by implementing https://github.com/brancz/kube-rbac-proxy/issues/259#issuecomment-2516553954.
It also aligns the behaviour of the `--oidc-ca-file` flag with [its description](https://github.com/brancz/kube-rbac-proxy/blob/28ede67b07bfa78103e78a4c4ce43560d6b15dba/cmd/kube-rbac-proxy/app/options/options.go#L126).
Reference to the code that utilises the host's root cert pool when no `CAContentProvider` is set https://github.com/kubernetes/kubernetes/blob/c83cbee114ddb732cdc06d3d1b62c9eb9220726f/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L271-L290
> OIDC authenticator defaults to using host's root CA pool if CA file is not provided

- pkg/server/config.go
We don't know the upstream HTTP version, there's likely no reason to force HTTP2 ever.
Fixes https://github.com/brancz/kube-rbac-proxy/issues/314
> allow HTTPv1 for upstream connections unconditionally

- pkg/authn/identityheaders/identityheaders.go
- pkg/authn/identityheaders/identityheaders_test.go
Add groups as separate header entries instead of concatenating them with a separator and update the corresponding unit test
Fixes: #330
> Put groups into separate header entries

- pkg/authorization/rewrite/attributes.go
While investigating a task #334 to consider `sync.Pool` in our code, I discovered that currently, each invocation of `templateWithValue` creates a new `bytes.Buffer` and discards it. By switching to a `sync.Pool` to reuse and reset these buffers, we can cut down on allocations and reduce overhead.
Here are the benchmark results I gathered using [`benchstat`](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) to compare `before_change.txt` (no `sync.Pool`) versus `after_change.txt` (using `sync.Pool`):
```
name                old time/op    new time/op    delta
TemplateWithValue-12    171.5ns ± 4%   145.4ns ± 0%  -15.19% (p=0.000 n=10)
name                old alloc/op   new alloc/op   delta
TemplateWithValue-12    192B ± 0%     80B ± 0%    -58.33% (p=0.000 n=10)
name                old …
```
> Reuse buffer with sync.Pool

- cmd/kube-rbac-proxy/app/options/proxyoptions.go
this ticket to resolve issue: [(25) Rename config file name to authz config filename as it is specific to authz](https://github.com/brancz/kube-rbac-proxy/issues/331)
> Rename config file name to authz config filename as it is specific to authz

- README.md
- cmd/kube-rbac-proxy/app/options/oidcoptions.go
- examples/oidc/deployment.yaml
- pkg/authn/config.go
- pkg/authn/oidc.go
- scripts/templates/oidc-deployment.yaml
Fixes: https://github.com/brancz/kube-rbac-proxy/issues/318
> explicitly require OIDC audience for the OIDC authenticator

- pkg/authn/oidc.go
Fix a nil pointer dereference introduced with https://github.com/brancz/kube-rbac-proxy/pull/342/commits/06bdb53ffd3f9062de96c4838ad7b51167b2b0f5.
Assigning `nil` type to an interface [fails a nil check later on](https://github.com/kubernetes/kubernetes/blob/7bd0477a95df377805373e5efc59598141113ece/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L284-L286) since the interface contains the type and its value.
Sorry for introducing this in the first place.
Before the change:
<details>
```
go run cmd/kube-rbac-proxy/main.go --kubeconfig=$KUBECONFIG --insecure-listen-address=0.0.0.0:8100 --oidc-clientID=foo  --oidc-issuer=https://accounts.google.com --upstream=http://localhost:3000
W0224 15:09:48.670407   81616 options.go:150] 
==== Deprecation Warning …
```
> pkg/authn: fix nil pointer dereference
