- Dockerfile
- Makefile
More reproducable than cross-compiling on your local box and injecting into a container
> Build containerised app in docker

- main.go
I haven't tested this, but it should work...
I've set the default to TLS 1.2, which aligns with the default k8s minimum TLS version.
> Make TLS version configurable

- auth/auth.go
- main.go
This pull request extracts the authentication parts with Kubernetes into a re-usable module to be importable by other projects.
@s-urbaniak @squat @mxinden
> Extract auth module

- CHANGELOG.md
- Dockerfile
- README.md
- examples/non-resource-url/README.md
- examples/non-resource-url/client-rbac.yaml
- examples/non-resource-url/client.yaml
- examples/oidc/.gitignore
- examples/oidc/README.md
- examples/oidc/client-rbac.yaml
- examples/oidc/deployment.yaml
- examples/resource-attributes/client-rbac.yaml
- examples/resource-attributes/client.yaml
- examples/resource-attributes/deployment.yaml
- examples/rewrites/README.md
- examples/rewrites/client-rbac.yaml
- examples/rewrites/deployment.yaml
- examples/rewrites/resource-attributes.yaml
- main.go
- scripts/generate-examples.sh
- scripts/templates/oidc-deployment.yaml
- scripts/templates/rewrites-deployment.yaml
> Prepare 0.4

- Dockerfile
Change  ARCH to GOARCH
@brancz sorry about this :(
> Change  ARCH to GOARCH

- main.go
Fixes #42 
@s-urbaniak @squat @metalmatze @paulfantom
> Host in self signed cert

- Dockerfile
- Makefile
- Make sure go modules are always enabled for better developer experience
- Use go1.12 in container image
/cc @brancz @s-urbaniak
> Minor tweaks to build process

- README.md
> README.md: Fix spelling and add link

- Dockerfile
Just wanted to update this before cutting v0.5.0.
@s-urbaniak @lilic @metalmatze
> Dockerfile: Use latest minor version of alpine

- CHANGELOG.md
@s-urbaniak @lilic @metalmatze
> *: Cut v0.5.0

- main.go
I got an error is "cannot find Service Account in pod to build in-cluster rest config",but I do not know why.
> cannot find Service Account in pod to build in-cluster rest config

- .github/workflows/build.yml
Migrated Travis CI/CD to GitHub Actions. Authentication to Quay with GitHub secrets. Related to issue #93
> GitHub Actions build file

- .github/workflows/build.yml
See https://github.com/engineerd/setup-kind/issues/28 for details.
> .github: update version of engineerd/setup-kind

- .github/workflows/build.yml
As suggested in https://github.com/brancz/kube-rbac-proxy/issues/108#issuecomment-769755271
cc @paulfantom
> build.yml: wait until images are available

- test/kubetest/kubernetes.go
This is a test to catch the flaky e2e failures.
Fixes #108
> test/kubetest: add dumpLogs, increase job backoff, ensure kube-rbac-proxy deployment is gone

- .github/workflows/build.yml
- scripts/publish.sh
> docker: build and publish multiarch images

- scripts/publish.sh
> scripts/publish: fetch tags

- main.go
- pkg/authn/delegating.go
> pkg/authn/delegating: dynamically reload client CA

- .github/workflows/build.yml
Porting fix from https://github.com/prometheus-operator/kube-prometheus/pull/1237
> Fix waiting for kind cluster in e2e tests

- .github/workflows/build.yml
> build.yml: increase linter timeout

- .github/workflows/build.yml
> github/workflows: fix golang setup for publish job

- README.md
- main.go
Emphasizes pattern matching in README.md
It seems to not be obvious: [issue](https://github.com/brancz/kube-rbac-proxy/issues/145).
> README.md: Emphasize pattern matching

- pkg/authn/delegating.go
- pkg/authz/auth.go
Add comments for better defaults.
Assumed origin of defaults.
It should serve as hint, which values would fit better in v1.
https://github.com/brancz/kube-rbac-proxy/pull/162#discussion_r834557270
https://github.com/brancz/kube-rbac-proxy/pull/162#discussion_r834547292
> Cache ttl comment

- pkg/authorization/rewrite/attributes.go
- pkg/authorization/rewrite/middleware.go
- Finish renaming.
- Add comments.
- Didn't complete renaming properly.
- Request to highlight the usage of client data from / to context.
> p/a/rewrite:finish renaming,add necessary comments

- cmd/kube-rbac-proxy/app/options/oidcoptions.go
this ticket to resolve issue: [(26) Add whitespace link](https://github.com/brancz/kube-rbac-proxy/issues/332)
> Add whitespace
